# Generated by Django 5.2.10 on 2026-09-02 18:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adminx", "0003_location_securityunit_securityunitcoverage_and_more"),
        ("streams", "0007_camera_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentIngestCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_identifier", models.CharField(max_length=500, unique=True)),
                ("byte_offset", models.PositiveBigIntegerField(default=0)),
                ("file_identity", models.CharField(blank=True, max_length=180)),
                ("last_event_id", models.CharField(blank=True, max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "source_system",
                    models.CharField(default="fight_runtime", max_length=80),
                ),
                ("run_id", models.CharField(max_length=100)),
                ("external_incident_id", models.CharField(max_length=180)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("FIGHT", "Fight"),
                            ("SPEED", "Speed"),
                            ("OTHER", "Other"),
                        ],
                        default="FIGHT",
                        max_length=20,
                    ),
                ),
                ("detected_at", models.DateTimeField()),
                ("finalized_at", models.DateTimeField()),
                (
                    "ingested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("routing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "routing_state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ROUTED", "Routed"),
                            ("UNROUTED", "Unrouted"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=80)),
                ("decision_score", models.FloatField(default=0.0)),
                ("max_score", models.FloatField(default=0.0)),
                ("mean_score", models.FloatField(default=0.0)),
                ("part_count", models.PositiveIntegerField(default=0)),
                ("evidence_path", models.CharField(blank=True, max_length=1000)),
                ("evidence_valid", models.BooleanField(default=False)),
                ("ingest_error", models.CharField(blank=True, max_length=500)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "acknowledged_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acknowledged_incidents",
                        to="adminx.securityunit",
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_incidents",
                        to="streams.camera",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="IncidentAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("INGESTED", "Ingested"),
                            ("ROUTED", "Routed"),
                            ("ROUTING_FAILED", "Routing failed"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("ESCALATED", "Escalated"),
                            ("RESOLVED", "Resolved"),
                        ],
                        max_length=30,
                    ),
                ),
                ("routing_stage", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incident_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="incidents.incident",
                    ),
                ),
                (
                    "security_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incident_audit_events",
                        to="adminx.securityunit",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="IncidentIngestRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=100, unique=True)),
                ("source_identifier", models.CharField(max_length=500)),
                ("byte_offset", models.PositiveBigIntegerField()),
                ("raw_envelope", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IMPORTED", "Imported"),
                            ("RETRYABLE", "Retryable"),
                            ("INVALID", "Invalid"),
                            ("DUPLICATE", "Duplicate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingest_records",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentRoutingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("FIGHT", "Fight"),
                            ("SPEED", "Speed"),
                            ("OTHER", "Other"),
                        ],
                        default="FIGHT",
                        max_length=20,
                    ),
                ),
                ("routing_stage", models.PositiveIntegerField(default=0)),
                ("delay_sec", models.PositiveIntegerField(default=0)),
                ("priority", models.IntegerField(default=100)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "security_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incident_routing_rules",
                        to="adminx.securityunit",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "incident_type",
                    "routing_stage",
                    "priority",
                    "security_unit__name",
                ],
            },
        ),
        migrations.CreateModel(
            name="IncidentRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("routing_stage", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("routed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=180)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_incident_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routes",
                        to="incidents.incident",
                    ),
                ),
                (
                    "security_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incident_routes",
                        to="adminx.securityunit",
                    ),
                ),
                (
                    "routing_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to="incidents.incidentroutingrule",
                    ),
                ),
            ],
            options={
                "ordering": ["incident", "routing_stage", "routed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["status", "routing_state"], name="incident_status_route_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["camera", "-detected_at"], name="incident_camera_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="incident",
            constraint=models.UniqueConstraint(
                fields=("source_system", "run_id", "external_incident_id"),
                name="unique_incident_source_run_external",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentauditevent",
            index=models.Index(
                fields=["incident", "created_at"], name="audit_incident_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="incidentingestrecord",
            index=models.Index(
                fields=["source_identifier", "byte_offset"],
                name="ingest_source_offset_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentroutingrule",
            index=models.Index(
                fields=["incident_type", "active", "routing_stage", "delay_sec"],
                name="routing_rule_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="incidentroutingrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("security_unit", "incident_type", "routing_stage"),
                name="unique_active_unit_incident_stage",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentroute",
            index=models.Index(
                fields=["security_unit", "status", "-routed_at"],
                name="route_unit_inbox_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="incidentroute",
            constraint=models.UniqueConstraint(
                fields=("incident", "security_unit", "routing_stage"),
                name="unique_incident_unit_stage_route",
            ),
        ),
    ]
