# Generated by Django 5.2.10 on 2026-09-02 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminx", "0003_location_securityunit_securityunitcoverage_and_more"),
        ("streams", "0006_merge_20260513_1836"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Yetkilendirmede kullanılan fiziksel lokasyon. Eski faculty alanı geçiş için korunur.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cameras",
                to="adminx.location",
                verbose_name="Fiziksel Lokasyon",
            ),
        ),
    ]
