# Generated by Django 5.2.13 on 2026-09-17 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminx", "0003_location_securityunit_securityunitcoverage_and_more"),
        ("streams", "0007_camera_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="source_kind",
            field=models.CharField(default="LIVE", editable=False, max_length=8),
        ),
        migrations.CreateModel(
            name="OfflineAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("file_path", models.CharField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "legacy_camera",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="streams.camera",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="adminx.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfflineRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("FIGHT", "Kavga"),
                            ("SPEED", "Hız"),
                            ("BOTH", "Kavga + Hız"),
                        ],
                        max_length=8,
                    ),
                ),
                ("configuration", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Bekliyor"),
                            ("PROCESSING", "İşleniyor"),
                            ("COMPLETED", "Tamamlandı"),
                            ("FAILED", "Başarısız"),
                            ("CANCELLED", "İptal edildi"),
                        ],
                        default="QUEUED",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("error", models.CharField(blank=True, max_length=100)),
                ("cancel_requested", models.BooleanField(default=False)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="streams.offlineasset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfflineResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(unique=True)),
                ("analysis_type", models.CharField(max_length=8)),
                ("video_time_sec", models.FloatField(null=True)),
                ("confidence", models.FloatField(null=True)),
                ("evidence_path", models.CharField(blank=True, max_length=1000)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="streams.offlinerun",
                    ),
                ),
            ],
        ),
    ]
