# Generated by Django 5.2.10 on 2026-09-02 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminx", "0002_alter_facultylocation_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180, verbose_name="Lokasyon adı")),
                (
                    "code",
                    models.SlugField(max_length=180, unique=True, verbose_name="Kod"),
                ),
                (
                    "location_type",
                    models.CharField(
                        default="other",
                        help_text="Örn: campus, faculty, building, floor, corridor, entrance, parking",
                        max_length=50,
                        verbose_name="Lokasyon tipi",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktif mi?")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="adminx.location",
                        verbose_name="Üst lokasyon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiziksel lokasyon",
                "verbose_name_plural": "Fiziksel lokasyonlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SecurityUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180, verbose_name="Birim adı")),
                (
                    "code",
                    models.SlugField(max_length=180, unique=True, verbose_name="Kod"),
                ),
                (
                    "unit_type",
                    models.CharField(
                        default="other", max_length=50, verbose_name="Birim tipi"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktif mi?")),
                (
                    "is_central",
                    models.BooleanField(
                        default=False, verbose_name="Merkezi birim mi?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_units",
                        to="adminx.location",
                        verbose_name="Ana lokasyon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Güvenlik birimi",
                "verbose_name_plural": "Güvenlik birimleri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SecurityUnitCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "include_descendants",
                    models.BooleanField(
                        default=True, verbose_name="Alt lokasyonları dahil et"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktif mi?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_coverages",
                        to="adminx.location",
                        verbose_name="Lokasyon",
                    ),
                ),
                (
                    "security_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverages",
                        to="adminx.securityunit",
                        verbose_name="Güvenlik birimi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Güvenlik birimi kapsamı",
                "verbose_name_plural": "Güvenlik birimi kapsamları",
                "ordering": ["security_unit__name", "location__name"],
            },
        ),
        migrations.CreateModel(
            name="UserSecurityAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktif mi?")),
                (
                    "role_in_unit",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Birim içi rol"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "security_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_assignments",
                        to="adminx.securityunit",
                        verbose_name="Güvenlik birimi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı güvenlik ataması",
                "verbose_name_plural": "Kullanıcı güvenlik atamaları",
                "ordering": ["user__username", "security_unit__name"],
            },
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["parent", "active"], name="location_parent_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["location_type", "active"], name="location_type_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityunit",
            index=models.Index(
                fields=["active", "is_central"], name="security_unit_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securityunitcoverage",
            index=models.Index(
                fields=["security_unit", "active"], name="coverage_unit_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="securityunitcoverage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("security_unit", "location"),
                name="unique_active_unit_location_coverage",
            ),
        ),
        migrations.AddIndex(
            model_name="usersecurityassignment",
            index=models.Index(
                fields=["user", "active"], name="assignment_user_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usersecurityassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("user", "security_unit"),
                name="unique_active_user_security_unit",
            ),
        ),
    ]
